version: '3.8'

services:
  kubepeek:
    build:
      context: .
      dockerfile: Dockerfile
    image: kubepeek:latest
    container_name: kubepeek
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ${HOME}/.kube:/root/.kube:ro
      - ${HOME}/.aws:/root/.aws:ro
    environment:
      - NODE_ENV=production
      - KUBECONFIG=/root/.kube/config 